'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Format
    Public Property id As Long
    Public Property Type As Nullable(Of Long)
    Public Property Name As String
    Public Property F1 As Nullable(Of Integer)
    Public Property F1comment As String
    Public Property F2 As Nullable(Of Integer)
    Public Property F2comment As String
    Public Property F3 As Nullable(Of Integer)
    Public Property F3comment As String
    Public Property F4 As Nullable(Of Integer)
    Public Property F4comment As String
    Public Property F5 As Nullable(Of Integer)
    Public Property F5comment As String
    Public Property F6 As Nullable(Of Integer)
    Public Property F6comment As String
    Public Property F7 As Nullable(Of Integer)
    Public Property F7comment As String
    Public Property F8 As Nullable(Of Integer)
    Public Property F8comment As String
    Public Property F9 As Nullable(Of Integer)
    Public Property F9comment As String
    Public Property F10 As Nullable(Of Integer)
    Public Property F10comment As String
    Public Property F11 As Nullable(Of Integer)
    Public Property F11comment As String
    Public Property F12 As Nullable(Of Integer)
    Public Property F12comment As String
    Public Property F13 As Nullable(Of Integer)
    Public Property F13comment As String
    Public Property F14 As Nullable(Of Integer)
    Public Property F14comment As String
    Public Property F15 As Nullable(Of Integer)
    Public Property F15comment As String
    Public Property FormatType As Nullable(Of Long)

End Class
