'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InputData
    Public Property id As Long
    Public Property crdate As Nullable(Of Date)
    Public Property type As Nullable(Of Long)
    Public Property txt As String
    Public Property split As String
    Public Property comment As String

End Class
