'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Sdb
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Sdb")
    End Sub

    Public Sub New(ConnectionString As String)
        MyBase.New(ConnectionString)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property InputDatas() As DbSet(Of InputData)
    Public Overridable Property Formats() As DbSet(Of Format)
    Public Overridable Property Logins() As DbSet(Of Login)
    Public Overridable Property Users() As DbSet(Of User)

End Class
